apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hands-on-app2-deployment
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        app: hands-on-app2
    spec:
      containers:
      - name: app2
        image: miyasakura/docker-hands-on-app2:latest
        ports:
        - containerPort: 4567

